### ISSUE TITLE
csa installation fails

### ISSUE THREAD

**Issue by ynodem** [INCF/csa#18]
Hi,
I try to install csa package with libneurosim. The installation of libneurosim with python support take place without any issues. When I try to install csa with these commands:
         **./autogen.sh
         ./configure ./configure --prefix=$HOME/opt/csa --with-libneurosim=$HOME/opt/libneurosim
         make**

The installation fails at the make step with these output errors:

   **_/home/yannick/Downloads/csa-master/libpycsa/pycsa.cpp:189: undefined reference to `PyGILState_Ensure'
/home/yannick/Downloads/csa-master/libpycsa/pycsa.cpp:190: undefined reference to `PyList_New'
/home/yannick/Downloads/csa-master/libpycsa/pycsa.cpp:197: undefined reference to `PyObject_CallFunctionObjArgs'
/home/yannick/Downloads/csa-master/libpycsa/pycsa.cpp:198: undefined reference to `PyList_SetItem'
/home/yannick/Downloads/csa-master/libpycsa/pycsa.cpp:202: undefined reference to `PyLong_FromLong'
/home/yannick/Downloads/csa-master/libpycsa/pycsa.cpp:202: undefined reference to `PyObject_CallFunctionObjArgs'
/home/yannick/Downloads/csa-master/libpycsa/pycsa.cpp:209: undefined reference to `PyGILState_Release'
.libs/libpycsa_la-pycsa.o: In function `error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/home/yannick/Downloads/csa-master/libpycsa/pycsa.cpp:53: undefined reference to `PyGILState_Release'
.libs/libpycsa_la-pycsa.o: In function `PyCSA::PyCSAGenerator::setMask(std::vector<ConnectionGenerator::Mask, std::allocator<ConnectionGenerator::Mask> >&, int)':
/home/yannick/Downloads/csa-master/libpycsa/pycsa.cpp:214: undefined reference to `PyGILState_Release'
collect2: error: ld returned 1 exit status
Makefile:444: recipe for target 'libpycsa.la' failed
make[2]: *** [libpycsa.la] Error 1
make[2]: Leaving directory '/home/yannick/Downloads/csa-master/libpycsa'
Makefile:420: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/yannick/Downloads/csa-master'
Makefile:350: recipe for target 'all' failed
make: *** [all] Error 2_**
 
I work on ubuntu 18.04 with python 3.7.3

Thank you

**Comment by ynodem** [comment]
Finally, I resolved the issues adding LDFLAGS="-L/home/yannick/opt/anaconda3/lib" option to ./configure. 
Thank
